// <auto-generated />
using System;
using BloodDonor.NewProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonor.NewProject.Migrations
{
    [DbContext(typeof(BloodDonorDbContext))]
    [Migration("20250717081553_AddSeedDataForBloodDonor")]
    partial class AddSeedDataForBloodDonor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDonor.Models.BloodDonorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("BloodDonors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroup = 0,
                            ContactNumber = "1234567890",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "John@gmail.com",
                            FullName = "John Doe",
                            Weight = 0f
                        },
                        new
                        {
                            Id = 2,
                            BloodGroup = 3,
                            ContactNumber = "0987654321",
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Jane@gmail.com",
                            FullName = "Jane Smith",
                            Weight = 0f
                        });
                });

            modelBuilder.Entity("BloodDonor.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodDonorEntityId")
                        .HasColumnType("int");

                    b.Property<int>("BloodDonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonorEntityId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BloodDonor.Models.Donation", b =>
                {
                    b.HasOne("BloodDonor.Models.BloodDonorEntity", null)
                        .WithMany("Donations")
                        .HasForeignKey("BloodDonorEntityId");
                });

            modelBuilder.Entity("BloodDonor.Models.BloodDonorEntity", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
